language: ruby
install: bundle install
script: rake build
deploy:
  provider: s3
  access_key_id: "${ACCESS}"
  secret_access_key: "${KEY}"
  bucket: "egee.xyz"
  region: us-west-2
  local_dir: _site
  skip_cleanup: true