language: ruby
install: cd "${TRAVIS_BUILD_DIR}/src" && bundle install
script: cd "${TRAVIS_BUILD_DIR}/src" && rake build
deploy:
  provider: s3
  access_key_id: "${ACCESS}"
  secret_access_key: "${KEY}"
  bucket: "egee.xyz"
  region: us-west-2
  acl: public_read
  local_dir: _site
  skip_cleanup: true
  on:
      branch: master
