title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Egee
repo_url: "https://github.com/egee-irl/egee-xyz"
edit_on_github: false
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
