title:       Egee.xyz
tagline:     "Personal Home Page"
description: "cluttered drawer of links"
url:         https://egee.xyz
permalink:   pretty
baseurl:     ''
paginate:    5

author:
  name: Egee
  url:  https://egee.xyz

plugins:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- Rakefile
- .jekyll-cache
- .gitignore
- .editorconfig
