title: Egee.xyz
tagline: "Personal Home Page"
description: "Egee's Home Page"
url: https://egee.xyz
permalink: pretty
baseurl: ""

author:
  name: Egee
  url: https://egee.xyz

plugins: []

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .jekyll-cache
  - .gitignore
  - .editorconfig
