require 'rake/clean'

task :serve do
  puts "Serving..."
  `bundle exec jekyll serve --livereload`
end

task :build do
  puts "Cleaning & Building..."
  `bundle exec jekyll clean`

  `bundle exec jekyll build`
  puts "Build complete! - ./src/_site"
end

task default: [:serve]
